name: Hello World

description: Greet someone and record the time

branding:
  icon: radio
  color: blue

inputs:
  greetee:
    description: Who to greet
    required: true
    default: World
  github_token:
    description: GitHub Personal Access Token (PAT) with sufficient permissions
    required: true

runs:
  using: docker
  image: "ghcr.io/asaaki/hello-world-docker-action:edge"
  args:
    - --greetee
    - ${{ inputs.greetee }}
    - --token
    - ${{ inputs.github_token }}

outputs:
  time:
    description: The time we greeted you
