name: 'Hello World'

description: 'Greet someone and record the time'

runs:
  using: 'docker'
  image: 'ghcr.io/asaaki/hello-world-docker-action:v0'
  args:
    - ${{ inputs.name }}

inputs:
  name: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'
