name: 'Hello World'

description: 'Greet someone and record the time'

branding:
  icon: 'radio'
  color: 'blue'

runs:
  using: 'docker'
  image: 'ghcr.io/asaaki/hello-world-docker-action:v0'
  args:
    - --name ${{ inputs.greetee }}
    - --token ${{ inputs.github_token }}

inputs:
  greetee: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github_token:
    description: 'GitHub Personal Access Token (PAT) with ??? permissions'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
