[package]
name = "action"
version = "0.1.0"
authors = ["Christoph Grabo <asaaki@mannaz.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[features]
default = ["rustls"]

rustls = ["surf/h1-client-rustls"]
openssl = ["surf/h1-client", "openssl-probe"]

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.9.0", features = ["attributes"] }
chrono = "0.4.19"
envconfig = "0.9.1"
openssl-probe = { version = "0.1.2", optional = true }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
surf = { version = "2.2.0", default-features = false, features = ["encoding"] }
structopt = "0.3.21"

# [patch.crates-io]
# # https://github.com/rust-lang/libc/pull/2119 - needs ~.91+ when released
# libc = { git = "https://github.com/rust-lang/libc.git", rev = "ac93582" }
