[package]
name = "action"
version = "0.1.0"
authors = ["Christoph Grabo <asaaki@mannaz.cc>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[features]
default = ["rustls"]

rustls = ["surf/h1-client-rustls"]
openssl = ["surf/h1-client", "openssl-probe"]

[dependencies]
anyhow = "1.0.98"
async-std = { version = "1.13.1", features = ["attributes"] }
chrono = "0.4.41"
envconfig = "0.11.0"
openssl-probe = { version = "0.1.6", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
surf = { version = "2.3.2", default-features = false, features = ["encoding"] }
structopt = "0.3.26"
