name: Hello World (Image Builder)

description: Greet someone and record the time

branding:
  icon: radio
  color: blue

inputs:
  greetee:
    description: Who to greet
    required: true
    default: World
  github_token:
    description: GitHub Personal Access Token with repo permissions
    required: true
  image_tag:
    description: Tag for the image
    required: true
    default: edge

runs:
  using: docker
  image: "ghcr.io/asaaki/hello-world-docker-action:${{ inputs.image_tag }}"
  args:
    - --greetee
    - "${{ inputs.greetee }}"
    - --token
    - "${{ inputs.github_token }}"

outputs:
  time: # id of output
    description: The time we greeted you
