# It should use the image just pushed to ghcr.io
ARG GITHUB_SHA=edge
FROM ghcr.io/asaaki/hello-world-docker-action:$GITHUB_SHA
LABEL org.opencontainers.image.source="https://github.com/asaaki/hello-world-docker-action"
