name: Docker image

on:
  push:
    branches: ['**']
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  pull_request_target:
    types: [labeled]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Create docker image

    steps:
    - uses: actions/checkout@v4

    - run: docker version
    - run: docker info
    - run: docker system df -v

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # https://github.com/docker/metadata-action
    - uses: docker/metadata-action@v5.7.0
      id: docker_meta
      with:
        images: |
          ghcr.io/asaaki/hello-world-docker-action
        tags: |
          type=edge,branch=main
          type=sha,prefix=git-
          type=sha,format=long,prefix=
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=ref,event=pr
          type=ref,event=branch
          type=schedule,pattern=nightly

    - uses: docker/login-action@v3.4.0
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - uses: docker/setup-buildx-action@v3.10.0
    - uses: docker/build-push-action@v6.16.0
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        platforms: linux/amd64

  self_test:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    name: Self tests the hello world docker action

    steps:
    - uses: actions/checkout@v4
    - name: Short SHA
      id: sha_short
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - name: Hello world action step
      id: hello # for use in step below
      uses: ./.image
      with:
        greetee: "${{ secrets.HELLO_SECRET_NAME }}"
        github_token: ${{ secrets.GHCR_PAT }}
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
