name: SelfTest

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: A job to say hello

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - run: docker pull ghcr.io/${{ github.repository }}:edge
    - name: Hello world action step
      id: hello # for use in step below
      uses: ./
      with:
        name: 'Self Test'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - run: docker system df -v
