name: SelfTest

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: A job to say hello

    steps:
    - uses: actions/checkout@v2
    - run: docker version
    - run: docker info
    - name: Hello world action step
      id: hello # for use in step below
      uses: ./
      with:
        name: 'Self Test'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
