name: Self Test

on:
  push:
    branches: [ "main" ]

jobs:
  self_test:
    runs-on: ubuntu-20.04
    name: Self tests the hello world docker action

    steps:
    - name: Hello world action step
      id: hello # for use in step below
      uses: ./
      with:
        name: 'Self Test User'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
