name: Self Test

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-20.04
    name: Self tests the hello world docker action

    steps:
    - uses: actions/checkout@v4
    - name: Hello world action step
      id: hello # for use in step below
      uses: ./
      with:
        greetee: 'Self Test User'
        github_token: ${{ secrets.GHCR_PAT }}
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
